export const WORD_COLLECTIONS: Record<string, string[]> = {
  Animals: ['LION', 'TIGER', 'ELEPHANT', 'GIRAFFE', 'MONKEY', 'ZEBRA', 'KANGAROO', 'PANDA', 'RABBIT', 'CHEETAH'],
  Vehicles: ['AIRPLANE', 'BICYCLE', 'SUBMARINE', 'HELICOPTER', 'SCOOTER', 'TRAIN', 'TRACTOR', 'ROCKET', 'YACHT'],
  Places: ['DESERT', 'ISLAND', 'VOLCANO', 'VALLEY', 'CANYON', 'GLACIER', 'FOREST', 'CASTLE', 'PYRAMID', 'HARBOR'],
  Food: ['BURGER', 'PIZZA', 'PANCAKE', 'NOODLES', 'SANDWICH', 'BURRITO', 'WAFFLE', 'POPCORN', 'SALAD', 'OMELET'],
  SciFi: ['CYBORG', 'GALAXY', 'QUANTUM', 'TELEPORT', 'ANDROID', 'NEBULA', 'GRAVITY', 'LASER', 'ASTEROID'],
  History: ['EMPIRE', 'KNIGHT', 'DYNASTY', 'PHARAOH', 'CRUSADE', 'CASTLE', 'VIKING', 'CHARIOT', 'TEMPLE'],
  Economy: ['MARKET', 'CAPITAL', 'INFLATION', 'TARIFF', 'REVENUE', 'FINANCE', 'EQUITY', 'BALANCE', 'EXPORT'],
  Biology: ['CELL', 'GENETICS', 'ORGANISM', 'ENZYME', 'SPECIES', 'PROTEIN', 'MITOSIS', 'MEMBRANE', 'BACTERIA'],
  Birds: ['EAGLE', 'FALCON', 'SPARROW', 'PEACOCK', 'PENGUIN', 'PARROT', 'OSTRICH', 'FLAMINGO', 'PELICAN'],
};

export type CollectionKey = keyof typeof WORD_COLLECTIONS;