import { useRef, useState } from 'react';
import Peer, { type DataConnection } from 'peerjs';
import { useGameStore } from '../store/gameStore';
import type { SocketAction } from '../types/game';

const PLAYER_COLORS = ['#ef4444', '#3b82f6', '#22c55e', '#eab308', '#a855f7'];

export const useGameNetwork = () => {
    const [peerId, setPeerId] = useState<string>('');
    const [isHost, setIsHost] = useState(false);
    const isHostRef = useRef(false);
    const peerRef = useRef<Peer | null>(null);
    const connectionsRef = useRef<DataConnection[]>([]);
    const hostConnectionRef = useRef<DataConnection | null>(null);

    const { setGameState, addPlayer, removePlayer } = useGameStore();

    // 1. Host a new game
    const hostGame = (playerName: string) => {
        setIsHost(true);
        isHostRef.current = true;

        // Initialize synchronously without Promises
        const peer = new Peer();

        peer.on('open', (id) => {
            setPeerId(id);
            peerRef.current = peer;
            // We only add the player AFTER the ID is generated by the server
            addPlayer({
                id,
                name: playerName,
                color: PLAYER_COLORS[0],
                score: 0,
                isHost: true,
            });
        });

        // Listen for incoming peer connections
        peer.on('connection', (conn) => {
            conn.on('open', () => {
                connectionsRef.current.push(conn);

                conn.on('data', (data) => {
                    handleIncomingAction(data as SocketAction, conn);
                });

                conn.on('close', () => {
                    connectionsRef.current = connectionsRef.current.filter((c) => c.peer !== conn.peer);
                    removePlayer(conn.peer);
                    broadcastState();
                    window.dispatchEvent(
                        new CustomEvent('peer-cursor-move', {
                            detail: { userId: conn.peer, x: -100, y: -100 },
                        })
                    );
                });
            });
        });
    };

    // 2. Join an existing game
    const joinGame = (hostId: string, playerName: string) => {
        setIsHost(false);
        isHostRef.current = false;

        const peer = new Peer();

        peer.on('open', (id) => {
            setPeerId(id);
            peerRef.current = peer;

            // Connect to host inside the open callback
            const conn = peer.connect(hostId.trim(), { reliable: true });
            hostConnectionRef.current = conn;

            conn.on('open', () => {
                conn.send({ type: 'JOIN_LOBBY', payload: { name: playerName } });
            });

            conn.on('data', (data) => {
                const action = data as SocketAction;

                if (action.type === 'SYNC_STATE') {
                    setGameState(action.payload);
                } else if (action.type === 'CURSOR_MOVE') {
                    window.dispatchEvent(
                        new CustomEvent('peer-cursor-move', {
                            detail: {
                                userId: action.payload.userId,
                                x: action.payload.x,
                                y: action.payload.y,
                            },
                        })
                    );
                }
            });

            conn.on('close', () => {
                alert('Disconnected from Host');
                useGameStore.getState().resetSession();
            });
        });
    };

    // 3. Centralized action handler (Host Authority)
    const handleIncomingAction = (action: SocketAction, senderConn: DataConnection) => {
        const senderId = senderConn.peer;
        const state = useGameStore.getState();

        switch (action.type) {
            case 'JOIN_LOBBY': {
                const colorIndex = Object.keys(state.players).length % PLAYER_COLORS.length;
                addPlayer({
                    id: senderId,
                    name: action.payload.name,
                    color: PLAYER_COLORS[colorIndex],
                    score: 0,
                    isHost: false,
                });

                // Delay sync by 50ms to ensure the peer data channel is ready to receive
                setTimeout(() => {
                    broadcastState();
                }, 50);
                break;
            }

            case 'WORD_FOUND': {
                const { word, cells } = action.payload;
                const isValidWord = state.wordsToFind.includes(word);
                const isAlreadyFound = !!state.foundWords[word];

                if (isValidWord && !isAlreadyFound) {
                    // 1. Lock in word & award points
                    useGameStore.getState().markWordFound(word, senderId, cells);
                    useGameStore.getState().updatePlayerScore(senderId, 10);

                    // 2. Broadcast the locked word immediately so players see it highlighted
                    broadcastState();

                    // 3. Check if this was the last word of the round
                    const updatedState = useGameStore.getState();
                    const allWordsFound =
                        Object.keys(updatedState.foundWords).length === updatedState.wordsToFind.length;

                    if (allWordsFound) {
                        // Small delay so players can see the completed board before advancing
                        setTimeout(() => {
                            if (updatedState.currentRound < updatedState.totalRounds) {
                                // Generate a brand new board and new words for the next round
                                useGameStore.getState().generateNewRound(updatedState.currentRound + 1);
                            } else {
                                // All rounds complete -> show final scoreboard
                                useGameStore.getState().setGameState({ status: 'scoreboard' });
                            }
                            broadcastState();
                        }, 700);
                    }
                }
                break;
            }
            case 'CURSOR_MOVE': {
                if (isHostRef.current) {
                    connectionsRef.current.forEach((conn) => {
                        if (conn.peer !== senderId && conn.open) {
                            conn.send({
                                type: 'CURSOR_MOVE',
                                payload: { ...action.payload, userId: senderId },
                            });
                        }
                    });
                }

                window.dispatchEvent(
                    new CustomEvent('peer-cursor-move', {
                        detail: {
                            userId: action.payload.userId || senderId,
                            x: action.payload.x,
                            y: action.payload.y,
                        },
                    })
                );
                break;
            }
        }
    };

    // Broadcast master state to all peers (Host only)
    const broadcastState = () => {
        if (!isHostRef.current) return;

        // 1. Destructure ONLY the data properties, ignoring the Zustand functions
        const {
            status, currentRound, totalRounds, players,
            board, wordsToFind, foundWords, foundCells
        } = useGameStore.getState();

        // 2. Package them into a clean, function-free object
        const safeState = {
            status, currentRound, totalRounds, players,
            board, wordsToFind, foundWords, foundCells
        };

        // 3. Send the clean state
        connectionsRef.current.forEach((conn) => {
            if (conn.open) {
                conn.send({ type: 'SYNC_STATE', payload: safeState });
            }
        });
    };
    const sendToHost = (action: SocketAction) => {
        if (isHostRef.current) {
            // Host processes their own action directly
            handleIncomingAction(action, { peer: peerRef.current?.id || 'host' } as DataConnection);
        } else if (hostConnectionRef.current && hostConnectionRef.current.open) {
            // Peers send to Host over WebRTC
            hostConnectionRef.current.send(action);
        }
    };
    const kickPlayer = (playerId: string) => {
        if (!isHostRef.current) return;

        // 1. Find and close peer connection
        const conn = connectionsRef.current.find((c) => c.peer === playerId);
        if (conn) {
            conn.close();
            connectionsRef.current = connectionsRef.current.filter((c) => c.peer !== playerId);
        }

        // 2. Remove from Zustand store
        useGameStore.getState().removePlayer(playerId);

        // 3. Broadcast updated roster to remaining players
        broadcastState();

        // 4. Remove cursor
        window.dispatchEvent(
            new CustomEvent('peer-cursor-move', {
                detail: { userId: playerId, x: -100, y: -100 },
            })
        );
    };
    return { peerId, isHost, hostGame, joinGame, sendToHost, broadcastState, kickPlayer };
};